### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by lyqht** [alisonthemonster/Presently#81]
Hello there! I just saw the app popping up in the Android Store recommendations and gave it a go. I really love the sleek theme and design of the app! Gonna be using this app rather frequently. Just wondering how else can a fan help with contribution to this app ? :)

**Comment by alisonthemonster** [comment]
Hi there! There are so many ways to help!

- Right now we're beta testing biometric authentication and the more devices we can test on the better! Sign up here to get on the beta list: https://forms.gle/LCk26Vrz2gkdrfZc7
- Translations are always welcome
- A user asked for an x or close button to be added to the milestone dialog
- One user wanted a random button in the calendar so they can view a random entry
- We want to add a link to the settings so you can share the app with your friends
- Setting to manually select language instead of having device select language

These are some suggestions, I'll create issues for potential features or improvements when I have more time 😄 Thanks so much for asking!

**Comment by lyqht** [comment]
Hi @alisonthemonster , thanks for the writeup! I'll try working on the following feature:
- A user asked for an x or close button to be added to the milestone dialog

Thank you!

**Comment by alisonthemonster** [comment]
#90 is the issue for an x button in the milestone dialog and I've created a few new issues for future contributors to work on :)
